name = "Iglu"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_robust/blob/master/LICENSE.md"
description = "Theme for Iglu Website"
tags = ["blog"]
features = ["blog"]
min_version = 0.1

[author]
    name = "André"
    homepage = "https://www.igluonline.com"
